--CREATE DATABASE [geraduo]

--USE [geraduo]

CREATE TABLE [Games]
(
	[Id] UNIQUEIDENTIFIER PRIMARY KEY NOT NULL,
	[Title] VARCHAR(40) NOT NULL,
	[BannerUrl] VARCHAR(255) NOT NULL
)


CREATE TABLE [Players]
(
	[Id] UNIQUEIDENTIFIER PRIMARY KEY NOT NULL,
    [Name] VARCHAR(90) NOT NULL,
	[NickName] VARCHAR(60) NOT NULL,
	[Email] VARCHAR(10) NOT NULL,
    [Password] VARCHAR(100) NOT NULL,
    [Discord] VARCHAR(50) NOT NULL,
    [createdAt] DATETIME NOT NULL,
    [uptadedAt] DATETIME NOT NULL DEFAULT(GETDATE())
)

CREATE TABLE [Ad]
(
    [Id] UNIQUEIDENTIFIER PRIMARY KEY NOT NULL,
    [PlayerId] UNIQUEIDENTIFIER NOT NULL,
    [GameId] UNIQUEIDENTIFIER NOT NULL,
    [WeekDays] VARCHAR(20) NOT NULL,
    [hourStart] INTEGER NOT NULL,
    [hourEnd] INTEGER NOT NULL,
    [createdAt] DATETIME NOT NULL,
    [uptadedAt] DATETIME NOT NULL DEFAULT(GETDATE())

	FOREIGN KEY ([PlayerId]) REFERENCES [Players]([Id])
)

